### PR TITLE
Adjust to match mzelinka

### PR DESCRIPTION
**Pull request by znicholls**
Looking at https://github.com/mzelinka/aprp/blob/b403fa0999af9ac66e7df9896ef1decc2aedbcc0/code/python/demonstrate_APRP.py#L162, I think this tweak is needed

### CODE REVIEW

**Comment by znicholls** [comment]
@chrisroadmap I think this change will increase your estimates by about 30%. I've asked Mark for some more help with his code (https://github.com/mzelinka/aprp/issues/1) but haven't heard back yet...

**Comment by chrisroadmap** [comment]
Well, re-reading the Zelinka reference I see this:

image

so the partial differentials in eq. A2 should be with respect to net TOA radiation and not downwelling TOA radiation, right?

When I get time I will check this implementation against the CMIP5 sstClimAerosol data.

**Comment by chrisroadmap** [comment]
Ran the CMIP5 data with this branch and the `ERFari` and `ERFaci` values are overestimated using `rsdt`. I think using `rsnt` and `rsntcs` is correct - I don't get an exact correspondence with Zelinka et al., 2014 using my original code but it is quite close. As a sense check, the total decomposition for `ERFari` + `ERFaci` + `albedo` should approximately add up to the total SW ERF where APRP can be used (true for sstClimAerosol in CMIP5 and piClim-aer in CMIP6). This happens (approximately) using `rsnt` but not with `rsdt`.

**Comment by znicholls** [comment]
> re-reading the Zelinka reference I see this

Aha good spot! So is there a bug in Mark's code or is that definition (R = rsnt rather than rsdt) just wrong or something else? (Something else seems most likely given your work with the CMIP5 data, I just can't work out why your code is giving similar answers to Mark's given they use different definitions of R). I also still don't understand how these derivations work given that the Taylor paper defines R = rsdt (see attached). 

[aprp_derivation.pdf](https://github.com/chrisroadmap/climateforcing/files/3694886/aprp_derivation.pdf)

**Comment by chrisroadmap** [comment]
Needs more thought from my side, but just to hammer a point:

image

image

where "sum" should approximately equal SW ERF, and the red and yellow highlights should correspond with the boxes in Zelinka figure 1.

**Comment by znicholls** [comment]
> just to hammer a point

Looks good. I just don't understand **why** it works and what the limitations are. In particular, why the definition of R changes between Taylor et al 2007 and Zelinka et al 2014, how to derive the equations actually used in the code and why we can't get it exactly correct (e.g. SW ERF ARI of -0.43 W/m^2 from your method vs. -0.38 W/m^2 from the Zelinka table is a difference of ~10%, which intuitively feels like more than just numerics).

**Comment by chrisroadmap** [comment]
Going to close this old pull request as can't get to the bottom of the differences, although logically the method I provide seems to be faithful to the intent of APRP, even if the implementation differs.

**Pull request closed without merging**
